
define \n


endef

TN_CALL_FROM_TASK     = \image html attr_call_task.png ${\n}\
                        \latexonly\
                        - call from task\
                        \endlatexonly

export TN_CALL_FROM_TASK



TN_CALL_FROM_ISR      = \image html attr_call_int.png ${\n} \
                        \latexonly\
                        - call from ISR\
                        \endlatexonly

export TN_CALL_FROM_ISR


TN_CALL_FROM_MAIN     = <i>call from main</i>

export TN_CALL_FROM_MAIN



TN_CAN_SWITCH_CONTEXT = \image html attr_call_ct_sw.png ${\n} \
                        \latexonly\
                        - can switch context\
                        \endlatexonly

export TN_CAN_SWITCH_CONTEXT

TN_CAN_SLEEP          = <i>can sleep</i>

export TN_CAN_SLEEP

all: 
	doxygen tn_doxyfile

